Names = [srotg,drotg,crotg,zrotg,
srotmg,drotmg,
srot,drot,csrot,zdrot,
srotm,drotm,
sswap,dswap,cswap,zswap,
sscal,dscal,cscal,csscal,zscal,zdscal,
scopy,dcopy,ccopy,zcopy,
saxpy,daxpy,caxpy,zaxpy,
sdot,ddot,cdotu,zdotu,
sdot,ddot,cdotc,zdotc,
sdsdot,dsdot,
snrm2,dnrm2,scnrm2,dznrm2,
sasum,dasum,scasum,dzasum,
isamax,idamax,icamax,izamax,
isamin,idamin, icamin, izamin,
ismax,idmax,icmax,izmax,
ismin,idmin, icmin, izmin,  

% LEVEL 2 
sgbmv, dgbmv, cgbmv, zgbmv,
ssbmv,dsbmv,
stbmv, dtbmv, ctbmv,ztbmv,
stbsv, dtbsv, ctbsv, ztbsv,
stpmv, dtpmv, ctpmv, ztpmv,
stpsv, dtpsv, ctpsv, ztpsv,
ssymv, dymv,
chemv, zhemv,
sspmv, dspmv,
sspr, dspr,
chpr, zhpr,
sspr2, dspr2,
chpr2, zhpr2,
chbmv, zhbmv,
chpmv, zhpmv,
sgemv, dgemv, cgemv, zgemv,

sger, dger, cgeru, cgerc, zgeru, zgerc,
cher, zher, cher2, zher2, 
strmv, dtrmv, ctrmv, ztrmv,
strsv, dtrsv, ctsv, ztrsv,



% LEVEL 3  
sgemm, dgemm, cgemm, cgemm3m, zgemm, zgemm3m,
chemm, zhemm,
cherk, zherk, cher2k, zher2k,
ssymm, dsymm, csymm, zsymm,

ssyrk, dsyrk, csyrk, zsyrk,
ssyr2k, dsyr2k, csyr2k, zsyr2k,
strmm, dtrmm, ctrmm, ztrmm,
strsm, dtrsm, ctrsm, ztrsm],

lists:foreach(fun({I,Name}) -> spawn(fun()-> timer:sleep( I*100), blas:run({Name})end) end, lists:zip(lists:seq(1, length(Names)), Names)).